language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.2"

sudo: false

cache:
  directories:
  - node_modules

env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
addons:
  firefox: "25.0"

before_script:
  - ./scripts/travis-install-slimerjs
  # we only need to run eslint once per build, so let's conserve a few resources
  - 'if [ "x$TRAVIS_NODE_VERSION" = "x0.12" ]; then $(npm bin)/eslint .; fi'

script:
  - ./scripts/ci-test.sh

git:
  depth: 10
