version: 2.1

references:
  x-workdir: &work-dir
    working_directory: ~/source

  x-save-workspace: &persist-step
    persist_to_workspace:
      root: ~/source
      paths:
        - .

  x-attach: &attach-step
    attach_workspace:
      at: .

jobs:
  install-dependencies:
    <<: *work-dir
    docker:
      - image: circleci/node:10
    environment:
      HUSKY_SKIP_INSTALL: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            if [ ! -d node_modules ]; then
                npm ci
            fi
      - save_cache:
          key: v2-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - *persist-step

  lint:
    <<: *work-dir
    docker:
      - image: node
    steps:
      - *attach-step
      - run:
          name: Lint
          command: npm run lint

  node-10:
    docker:
      - image: circleci/node:10
    steps:
      - *attach-step
      - run:
          name: Test
          command: npm run test-node

  node-12:
    docker:
      - image: circleci/node:12
    steps:
      - *attach-step
      - run:
          name: Test
          command: npm run test-node

  node-14:
    docker:
      - image: circleci/node:14
    steps:
      - *attach-step
      - run:
          name: Test
          command: npm run test-node

  integration-tests:
    docker:
      - image: circleci/node:10.15.1-browsers
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    steps:
      - *attach-step
      - run:
          name: Integration tests
          command: |
            # test-coverage runs test-headless in Chrome
            npm run test-coverage  -- --chrome "$SINON_CHROME_BIN" --allow-chrome-as-root
            npm run test-webworker -- --chrome "$SINON_CHROME_BIN" --allow-chrome-as-root
            npm run test-esm-bundle

            if [ -z "$CIRCLE_PULL_REQUESTS" ]; then
              npm run test-cloud
            fi
      - run:
          name: Upload coverage report
          command: bash <(curl -s https://codecov.io/bash) -F unit -s coverage/lcov.info

  saucelabs:
    docker:
      - image: circleci/node:12
    steps:
      - *attach-step
      - run:
          name: Test in browsers (Sauce Labs)
          command: npm run test-cloud

workflows:
  version: 2
  sinon-workflow:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - node-10:
          requires:
            - install-dependencies
      - node-12:
          requires:
            - install-dependencies
      - node-14:
          requires:
            - install-dependencies
      - integration-tests:
          requires:
            - install-dependencies
            - lint
            - node-10
            - node-12
            - node-14
      - saucelabs:
          context: SAUCE_LABS
          requires:
            - integration-tests
          filters:
            branches:
              only: master
